### Variables
@baseUrl = http://localhost:3000
@contentType = application/json
@testEmail = test@example.com
@testPassword = newpassword123
@testName = testuser

### Register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "{{testEmail}}",
  "password": "{{testPassword}}",
  "name": "{{testName}}"
}

### Login(200)
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "{{testEmail}}",
  "password": "{{testPassword}}"
}

### Login(400)
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "{{testEmail}}",
  "password": "wrongpassword"
}